-- Supabase Database Schema for AyuRoots (Ayurvedic Hair Care)

-- 1. Profiles Table (Extends Supabase Auth users)
CREATE TABLE public.profiles (
    id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name text,
    mobile text,
    role text DEFAULT 'user'::text CHECK (role IN ('user', 'admin')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Categories Table
CREATE TABLE public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Products Table
CREATE TABLE public.products (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL,
    price numeric NOT NULL,
    discount_price numeric,
    stock integer NOT NULL DEFAULT 0,
    ingredients text,
    benefits text,
    usage text,
    category_id bigint REFERENCES public.categories(id) ON DELETE SET NULL,
    images text[], -- Array of image URLs
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Orders Table
CREATE TABLE public.orders (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    total_amount numeric NOT NULL,
    payment_method text NOT NULL, -- e.g., 'COD', 'Online'
    payment_status text DEFAULT 'Pending'::text, -- 'Pending', 'Paid', 'Failed'
    order_status text DEFAULT 'Pending'::text, -- 'Pending', 'Approved', 'Processing', 'Shipped', 'Out for Delivery', 'Delivered', 'Completed', 'Rejected'
    shipping_address jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Order Items Table
CREATE TABLE public.order_items (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
    quantity integer NOT NULL,
    price numeric NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Reviews Table
CREATE TABLE public.reviews (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    product_id uuid REFERENCES public.products(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Wishlist Table
CREATE TABLE public.wishlist (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    product_id uuid REFERENCES public.products(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Basic Policies
-- Profiles: Users can read/update their own profile. Admins can read all.
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Products: Everyone can read. Only admins can insert/update/delete.
CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (true);
-- (Admin policies would require checking the profile role, usually handled via backend Admin SDK bypassing RLS or complex RLS functions)

-- Orders: Users can read their own orders. Admins can read all.
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);

-- 8. Payments Table
CREATE TABLE public.payments (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
    payment_gateway_id text,
    signature text,
    amount numeric NOT NULL,
    status text DEFAULT 'Pending'::text CHECK (status IN ('Pending', 'Success', 'Failed', 'Refunded')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. OTP Verifications Table
CREATE TABLE public.otp_verifications (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    mobile text NOT NULL,
    otp_hash text NOT NULL,
    status text DEFAULT 'Pending'::text CHECK (status IN ('Pending', 'Verified', 'Expired')),
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Delivery Tracking Table
CREATE TABLE public.delivery_tracking (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
    delivery_partner_name text,
    status text DEFAULT 'Assigned'::text CHECK (status IN ('Assigned', 'Picked Up', 'In Transit', 'Out for Delivery', 'Delivered', 'Failed Attempt')),
    location_data jsonb,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Notifications Table
CREATE TABLE public.notifications (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    title text NOT NULL,
    message text NOT NULL,
    type text NOT NULL CHECK (type IN ('order', 'payment', 'alert', 'delivery')),
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for new tables
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Additional Policies
CREATE POLICY "Users can view own payments" ON public.payments FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.orders WHERE orders.id = payments.order_id AND orders.user_id = auth.uid())
);
CREATE POLICY "Users can view own delivery tracking" ON public.delivery_tracking FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.orders WHERE orders.id = delivery_tracking.order_id AND orders.user_id = auth.uid())
);
CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

-- 12. Contact Messages Table
CREATE TABLE public.contact_messages (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    subject text NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: No RLS required if we want to allow public unauthenticated inserts via backend or if the backend uses Service Role
